[platformio]
default_envs = orbital_esp32dev

[env:orbital_esp32dev]
extends = env:esp32dev
custom_usermods = audioreactive
build_unflags = ${env:esp32dev.build_unflags}
  -D WLED_ENABLE_DMX_INPUT
build_flags = ${env:esp32dev.build_flags}
  -D UM_AUDIOREACTIVE_ENABLE
  -D SR_DMTYPE=1
  -D I2S_SDPIN=32
  -D I2S_WSPIN=26
  -D I2S_CKPIN=27
  -D MCLK_PIN=-1
  -D WLED_DISABLE_ALEXA
  -D WLED_DISABLE_HUESYNC
  -D WLED_DISABLE_INFRARED
  -D WLED_DISABLE_MQTT
  -D WLED_DISABLE_LOXONE
  -D WLED_DISABLE_ESPNOW
  -D WLED_DISABLE_2D
  -D WLED_DISABLE_PARTICLESYSTEM1D
  -D WLED_DISABLE_PARTICLESYSTEM2D
  -D WLED_DISABLE_PIXELFORGE
lib_ignore = ${env:esp32dev.lib_ignore}
  esp_dmx
  IRremoteESP8266
  AsyncMqttClient
  wled-espnow
